version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: 'm-container'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - "27017:27017"
    volumes:
      - data:/data

  postgresdb:
    image: postgres
    container_name: 'pdb-container'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

volumes:
  data: {}
